"""
build_parts.py — slice each cleaned concept sprite (assets/<key>.png, already
background-free) into rig parts so the detailed art can be SKELETALLY ANIMATED
in the game (cut-out animation): a 'top' chunk (torso + head + arms + weapon)
and two legs that swing from the hip. Robe/no-leg characters stay single-piece.

Run:  py -3 tools/build_parts.py
Reads ./assets/<key>.png  ->  ./assets/parts/<key>_{top,legF,legB}.png + assets/rig.json
"""
import os, json
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
PARTS = os.path.join(ASSETS, "parts")
os.makedirs(PARTS, exist_ok=True)

# per character: hip line (fraction of height), centre x (fraction of width), has legs
CFG = {
    "ragnarok":  {"hip": 0.55, "cx": 0.47, "legs": True},
    "zracks":    {"hip": 0.48, "cx": 0.47, "legs": True},
    "zombie":    {"hip": 0.57, "cx": 0.46, "legs": True},
    "werewolf":  {"hip": 0.53, "cx": 0.47, "legs": True},
    "dragonman": {"hip": 0.56, "cx": 0.50, "legs": True},
    "demon":     {"hip": 0.58, "cx": 0.48, "legs": True},
    "flayer":    {"hip": 0.60, "cx": 0.50, "legs": False},
}


def slice_one(key, cfg):
    path = os.path.join(ASSETS, key + ".png")
    if not os.path.exists(path):
        print("MISSING", path); return None
    im = Image.open(path).convert("RGBA")
    W, H = im.size
    hip = round(H * cfg["hip"]); cx = round(W * cfg["cx"])
    ov = max(2, round(H * 0.05))            # overlap so joints never gap
    entry = {"w": W, "h": H, "cx": cx, "hip": hip, "legs": cfg["legs"]}

    if not cfg["legs"]:
        im.save(os.path.join(PARTS, key + "_top.png"))
        entry["parts"] = {"top": [0, 0, W, H]}
        return entry

    top = im.crop((0, 0, W, hip))
    legF = im.crop((max(0, cx - ov), max(0, hip - ov), W, H))
    legB = im.crop((0, max(0, hip - ov), min(W, cx + ov), H))
    top.save(os.path.join(PARTS, key + "_top.png"))
    legF.save(os.path.join(PARTS, key + "_legF.png"))
    legB.save(os.path.join(PARTS, key + "_legB.png"))
    entry["parts"] = {
        "top":  [0, 0, W, hip],
        "legF": [max(0, cx - ov), max(0, hip - ov), W, H],
        "legB": [0, max(0, hip - ov), min(W, cx + ov), H],
    }
    return entry


def main():
    rig = {}
    for key, cfg in CFG.items():
        e = slice_one(key, cfg)
        if e: rig[key] = e; print("ok", key, "hip", e["hip"], "cx", e["cx"], "legs", e["legs"])
    with open(os.path.join(ASSETS, "rig.json"), "w", encoding="utf-8") as f:
        json.dump(rig, f, indent=2)
    # also emit a JS file (file:// can't fetch JSON, but can <script> it)
    with open(os.path.join(ROOT, "js", "rigdata.js"), "w", encoding="utf-8") as f:
        f.write("/* generated by tools/build_parts.py */\nconst RIG_DATA = " + json.dumps(rig) + ";\n")
    print("wrote rig.json + js/rigdata.js for", len(rig), "characters")


if __name__ == "__main__":
    main()
